import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
//layout for webpage
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //added header inside body wrapping children so header will always show
  return (
    <html lang='en'>
      <body className={inter.className}>
        <h1>Header</h1>
        {children}
      </body>
    </html>
  );
}
